name: Nightly Build

on:
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  security-events: write

jobs:

  Publish:
    uses: eclipse-edc/.github/.github/workflows/nightly.yml@main
    secrets: inherit
    with:
      test-tag-exclusions: OtcTest,GaussDbTest
