name: Release

on:
  workflow_dispatch:

permissions:
  actions: read
  contents: write
  security-events: write

jobs:

  Release:
    uses: eclipse-edc/.github/.github/workflows/release.yml@main
    secrets: inherit
