name: Release

on:
  workflow_dispatch:

permissions:
  actions: read
  contents: write
  security-events: write

jobs:

  Run-Tests:
    uses: ./.github/workflows/verify.yaml
    secrets: inherit

  Release:
    uses: eclipse-edc/.github/.github/workflows/technology-release.yml@main
    secrets: inherit
