name: Run Tests

permissions:
  actions: read
  contents: read
  security-events: write

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [ main, release/*, bugfix/* ]
  pull_request:
    branches: [ main, release/*, bugfix/* ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'CODEOWNERS'
      - 'LICENSE'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  CodeQL:
    uses: eclipse-edc/.github/.github/workflows/codeql-analysis.yml@main
    secrets: inherit

  Checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: eclipse-edc/.github/.github/actions/setup-build@main
      - name: Run Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest

  Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: eclipse-edc/.github/.github/actions/setup-build@main

      - name: Run unit tests
        run: ./gradlew test

  Component-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: eclipse-edc/.github/.github/actions/setup-build@main

      - name: Component Tests
        run: ./gradlew -DincludeTags="ComponentTest"

  Integration-Tests:
    uses: ./.github/workflows/integration-tests.yaml
    secrets: inherit

  API-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: eclipse-edc/.github/.github/actions/setup-build@main

      - name: Component Tests
        run: ./gradlew test -DincludeTags="ApiTest"
